version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mariadb:latest
    container_name: mariadb-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=r@@t
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    restart: always


  #service 2: definition of phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: r@@t



  #service 3: definition of your spring-boot app
  abstractionapp:                        #it is just a name, which will be used only in this file.
    image: abstraction-app               #name of the image after dockerfile executes
    container_name: abstraction-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8085:8085"                       #docker containter port with your os port
    #restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/abstraction-app?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: r@@t
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
      spring.datasource.driver-class-name: org.mariadb.jdbc.Driver
      spring.datasource.initialization-mode: always